name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Generate ZIP
        run: 
          zip deployment.zip *.mjs
      - name: 297616695535_AdministratorAccess deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{secrets.AWS_SESSION_TOKEN}}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: firstFunction
          zip_file: deployment.zip
      
